name: "Build on Windows"

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  BOOST_VERSION: "1.82.0"
  CMAKE_GENERATOR: "Visual Studio 17 2022"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        architecture: [ "arm64", "x64" ]
        include:
          - architecture: arm64
            CMAKE_GENERATOR_PLATFORM: "ARM64EC"
          - architecture: x64
            CMAKE_GENERATOR_PLATFORM: "x64"
    runs-on: "windows-2022"
    name: "Windows (${{ matrix.architecture }})"
    env:
      CMAKE_GENERATOR_PLATFORM: "${{ matrix.CMAKE_GENERATOR_PLATFORM }}"
    steps:
    - name: "Clone"
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

# Boost Library
    - name: Cache Boost
      uses: actions/cache@v2
      with:
        path: '${{ runner.workspace }}/boost_*.tar.gz'
        key: 'boost-${{ env.BOOST_VERSION }}'
    - name: Build Boost
      id: boost
      uses: egor-tensin/build-boost@v1
      with:
        version: ${{ env.BOOST_VERSION }}
        libraries: asio
        static: true
        static-runtime: true

    - name: "Configure"
      continue-on-error: true
      shell: bash
      run: |
        cmake \
          -S "${{ github.workspace }}" \
          -B "${{ github.workspace }}/build/devel" \
          -DCMAKE_PREFIX_PATH=${ steps.boost.outputs.root } \
          -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/build/distrib"

    - name: "Build"
      continue-on-error: true
      shell: bash
      env:
        CMAKE_BUILD_TYPE: "RelWithDebInfo"
      run: |
        cmake --build "build/devel" --config ${{ env.CMAKE_BUILD_TYPE }} --target install

    - name: "Artifacts"
      uses: actions/upload-artifact@v1
      with:
        name: "windows-${{ matrix.architecture }}"
        path: "${{ github.workspace }}/build/distrib"
